### PR TITLE
Flutter 3 + widget to simplify use a lot

### PR DESCRIPTION
**Pull request by ikbendewilliam**

### CODE REVIEW

**Comment by vjamrich** [comment]
This looks great!

**Comment by ikbendewilliam** [comment]
@hathibelagal-dev can you take a look at this? 
I've tried to notify them through twitter aswel, as this is the only social I could find 😬. 
Otherwise I'm thinking of publishing it under my name. WDYT @vjamrich?

**Comment by vjamrich** [comment]
@ikbendewilliam I think there is a need for an updated version of this package and the community would greatly benefit from it.

I have been using my own modified version of it for quite some time (based on the one you initially forked) and have been considering doing a complete rewrite together with an implementation of a widget.

**Comment by ikbendewilliam** [comment]
Alright. I'm going to look into it. I'll probably upload it to pub.dev again and make you maintainer as well.

**Comment by ikbendewilliam** [comment]
[GitHub](https://github.com/ikbendewilliam/path_morph_for_flutter)
[pub.dev](https://pub.dev/packages/flutter_path_morph)

**Pull request closed without merging**
